const express=require('express'),Database=require('better-sqlite3'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path'),fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE_ME';fs.mkdirSync('data',{recursive:true});const db=new Database('data/duhuza.db');db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,email TEXT UNIQUE,password TEXT,age INTEGER,gender TEXT,city TEXT,bio TEXT,interests TEXT,looking_for TEXT,photo TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS likes(a INTEGER,b INTEGER,UNIQUE(a,b));CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,chat TEXT,sender INTEGER,body TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS blocks(a INTEGER,b INTEGER,UNIQUE(a,b));CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY,reporter INTEGER,reported INTEGER,reason TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare('SELECT 1 FROM users LIMIT 1').get()){let p=bcrypt.hashSync('demo12345',10),s=db.prepare('INSERT INTO users(name,email,password,age,gender,city,bio,interests,looking_for,photo) VALUES(?,?,?,?,?,?,?,?,?,?)');[['Aline','aline@demo.duhuza',24,'female','Kigali','Nkunda music no gutembera.','Music, Travel','Inshuti cyangwa umukunzi','https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=700'],['Eric','eric@demo.duhuza',27,'male','Huye','Nshaka kumenya abantu bashya.','Football, Tech','Umubano mwiza','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=700'],['Shalom','shalom@demo.duhuza',23,'female','Musanze','Nshimishwa n’ibiganiro byiza.','Fashion, Music','Umuntu w’inyangamugayo','https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=700']].forEach(x=>s.run(x[0],x[1],p,x[2],x[3],x[4],x[5],x[6],x[7],x[8]));}
app.use(express.json());app.use(express.static('public'));const pub=u=>({id:u.id,name:u.name,age:u.age,gender:u.gender,city:u.city,bio:u.bio,interests:u.interests,lookingFor:u.looking_for,photo:u.photo});const tok=u=>jwt.sign({id:u.id},SECRET,{expiresIn:'7d'});function auth(req,res,next){try{let h=req.headers.authorization||'';req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch{return res.status(401).json({error:'Ongera winjire.'})}}
app.post('/api/register',(req,res)=>{let x=req.body;if(!x.name||!x.email||!x.password||!x.age||!x.city)return res.status(400).json({error:'Uzuza ibisabwa.'});if(+x.age<18)return res.status(400).json({error:'Duhuza ni 18+.'});try{let info=db.prepare('INSERT INTO users(name,email,password,age,gender,city,bio,interests,looking_for,photo) VALUES(?,?,?,?,?,?,?,?,?,?)').run(x.name,x.email.toLowerCase(),bcrypt.hashSync(x.password,10),+x.age,x.gender,x.city,x.bio||'',x.interests||'',x.lookingFor||'',x.photo||'');let u=db.prepare('SELECT * FROM users WHERE id=?').get(info.lastInsertRowid);res.json({token:tok(u),user:pub(u)})}catch(e){res.status(409).json({error:'Email isanzwe ikoreshwa.'})}});
app.post('/api/login',(req,res)=>{let u=db.prepare('SELECT * FROM users WHERE email=?').get((req.body.email||'').toLowerCase());if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Email cyangwa password si byo.'});res.json({token:tok(u),user:pub(u)})});app.get('/api/me',auth,(req,res)=>res.json({user:pub(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id))}));
app.get('/api/discover',auth,(req,res)=>{let q='%'+(req.query.q||'')+'%',city=req.query.city||'',sql='SELECT * FROM users WHERE id<>? AND name LIKE ? AND city LIKE ? ORDER BY id DESC LIMIT 60';res.json({users:db.prepare(sql).all(req.user.id,q,city||'%').map(pub)})});
app.post('/api/like/:id',auth,(req,res)=>{let id=+req.params.id;db.prepare('INSERT OR IGNORE INTO likes(a,b) VALUES(?,?)').run(req.user.id,id);res.json({match:!!db.prepare('SELECT 1 FROM likes WHERE a=? AND b=?').get(id,req.user.id)})});
app.get('/api/matches',auth,(req,res)=>res.json({matches:db.prepare('SELECT u.* FROM users u JOIN likes l ON l.b=u.id WHERE l.a=? AND EXISTS(SELECT 1 FROM likes z WHERE z.a=u.id AND z.b=?)').all(req.user.id,req.user.id).map(pub)}));
function key(a,b){return [a,b].sort((x,y)=>x-y).join(':')}app.get('/api/messages/:id',auth,(req,res)=>res.json({messages:db.prepare('SELECT * FROM messages WHERE chat=? ORDER BY id').all(key(req.user.id,+req.params.id))}));app.post('/api/messages/:id',auth,(req,res)=>{let body=String(req.body.body||'').trim();if(!body)return res.status(400).json({error:'Ubutumwa burimo ubusa.'});db.prepare('INSERT INTO messages(chat,sender,body) VALUES(?,?,?)').run(key(req.user.id,+req.params.id),req.user.id,body);res.json({ok:true})});
app.post('/api/block/:id',auth,(req,res)=>{db.prepare('INSERT OR IGNORE INTO blocks(a,b) VALUES(?,?)').run(req.user.id,+req.params.id);res.json({ok:true})});app.post('/api/report/:id',auth,(req,res)=>{db.prepare('INSERT INTO reports(reporter,reported,reason) VALUES(?,?,?)').run(req.user.id,+req.params.id,String(req.body.reason||'Konti idakwiriye'));res.json({ok:true})});app.get('/{*splat}',(req,res)=>res.sendFile(path.resolve('public/index.html')));app.listen(PORT,()=>console.log('Duhuza: http://localhost:'+PORT));
